site_name: PottingPvP
repo_name: 'Kore-Development/pottingpvp-docs'
repo_url: 'https://github.com/Kore-Development/pottingpvp-docs'
theme:
  name: material
  language: 'en'
  favicon: 'favicon.ico'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  logo:
    icon: 'games'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
